### PR TITLE
Add module for redis support

### PR DESCRIPTION
**Pull request by kromonos**
Add redis module

### CODE REVIEW

**Comment by andrewgodwin** [comment]
You've failed the linting for that file - you can either get pre-commit installed and have it fix them (instructions in our contributing docs) or you can manually sort the file!

**Comment by kromonos** [comment]
> You've failed the linting for that file - you can either get pre-commit installed and have it fix them (instructions in our contributing docs) or you can manually sort the file!

oh. So I just need to place the redis line under `python-dotenv~=0.21.0` instead at the end of the file?

**Comment by andrewgodwin** [comment]
Yup, our linters enforce that it's sorted.

**Comment by andrewgodwin** [comment]
Thanks!

**Pull request merged**
