### PR TITLE
Flexible uploads

### PR DESCRIPTION
**Pull request by TkTech**
This allows uploading and download arbitrary file types. Note this PR is based on the changes in #242.

Uploading:

image

Downloading:

[arbitrary_uploads.webm](https://user-images.githubusercontent.com/72590/209391381-ca22d393-5b49-4f63-9acd-db1441792255.webm)

### CODE REVIEW

**Comment by TkTech** [comment]
@andrewgodwin the one thing we need to do if possible is populate the `original_filename` on PostAttachment with INBOUND filenames, if they're available somehow .

**Comment by andrewgodwin** [comment]
Due to the size of this I'm going to delay review/merging of it until after 0.6 is cut!

**Comment by TkTech** [comment]
Converted this into a draft, will clean up the tree and splice in two.

**Review by andrewgodwin — COMMENTED** [review]
Two comments:

- There's already a 0008 migration on main now, you'll need to rebase this one
- If you want to capture the filename on remote attachments, the only one we have is the end of the `attachment["url"]` in `Post.by_ap`.

**Comment by andrewgodwin** [comment]
Given I've ripped _out_  a lot of the compose upload code now, closing this out, as we'd have to focus on the API uploads only instead.

**Pull request closed without merging**
