### PR TITLE
Make max media upload size configurable

### PR DESCRIPTION
**Pull request by aviflax**
As some of us want to upload full-size photos and videos.

I’m pretty rusty with Django so sorry if this isn’t the idiomatic way to access the setting from a view. Please let me know if not, and I’ll fix this.

I hope to propose a follow-up change that’ll make the max image dimensions configurable. After that, someone should be able to configure their installation such that they’d be able to post, say, a 14 megabyte file of a 25 megapixel photo, and have it be uploaded, saved, and attached to a post, at the original fidelity. If so desired.

### CODE REVIEW

**Comment by andrewgodwin** [comment]
It's worth noting why this is in place - Mastodon's image proxy won't support super large images, so we forcibly scale all uploaded media down so it's an acceptable size to give out to Mastodon so it can load them (2000x2000). That means increasing the uploaded media size will merely give the resizer more work to do and not keep the originals around.

If you also want to keep the originals, we will need to add a third FileField to PostAttachment that stores the original image, and then not send that over ActivityPub or client APIs but only use it when viewed locally. I opted not to do that yet because of the very small utility.

**Comment by andrewgodwin** [comment]
Yes, that's a good point - this is more just a setting right now of "how much RAM did you give the web process?". 

With that in mind, can we rename the setting to `MEDIA_MAX_IMAGE_FILESIZE`? That way it lines up with the other media settings, and we can also implement an alternative one when we get to videos, as those need background processing anyway.

**Comment by aviflax** [comment]
> Yes, that's a good point - this is more just a setting right now of "how much RAM did you give the web process?".

👍
 
> With that in mind, can we rename the setting to `MEDIA_MAX_IMAGE_FILESIZE`? That way it lines up with the other media settings, and we can also implement an alternative one when we get to videos, as those need background processing anyway.

Of course. How would you feel about adding the suffix `_MB` to make the units clear? I know the resulting var name is pretty long, but I find it really helpful when numeric configs indicate the units right in the name.

**Comment by andrewgodwin** [comment]
Yup, agreed, let's stick the unit on there. Better to be explicit.

**Comment by aviflax** [comment]
Done via 56ec2e0a55da372b62847505de2a07b19aadde80

**Comment by aviflax** [comment]
apropos to the shelved-for-now notion of increasing image resizing dimensions, I found an ongoing and in-depth discussion of image resolutions here: mastodon/mastodon#20255

**Comment by andrewgodwin** [comment]
Thanks. That issue you linked does seem rather split - there's definitely a "phone cameras will just burp out giant files" versus "artists want to preserve their work" split. Odd that Mastodon forces everything to low-quality JPEG, though, not webp, given the compatibility of the latter!

**Pull request merged**
