### PR TITLE
Fix #471

### LINKED ISSUE #471: Visible follows setting should not apply to post count
Default view for profile
11 posts 12 following 13 followers

After changing _visible follows_ settings to disable, the profile shows this
[blank] [blank] [blank]

The profile should show this instead
11 posts [blank] [blank]

### PR DESCRIPTION
**Pull request by okpierre**
-hide following and followers count
-exclude post count

https://github.com/jointakahe/takahe/issues/471

### CODE REVIEW

**Comment by shuuji3** [comment]
Hello, I think your code change is appropriate but you also need to amend the related test here: https://github.com/jointakahe/takahe/blob/f967f6c6971b7c34831432c579720c93a2da15e5/tests/users/views/settings/test_privacy.py#L19-L29

The current test code supposes that the entire `<div class="view-options follows">` is hidden when this feature is enabled.

**Comment by okpierre** [comment]
> The current test code supposes that the entire `<div class="view-options follows">` is hidden when this feature is enabled.

Hello @shuuji3 thank you for sharing your input. 

I looked at the source and it shows this

takahevisiblefollowsdiv

I can also place the post count and the follows into two separate divs if that helps pass the checks. Would that be better?

**Comment by shuuji3** [comment]
I think we can change to check the existance of `follower` string instead of `div` in https://github.com/jointakahe/takahe/blob/f967f6c6971b7c34831432c579720c93a2da15e5/tests/users/views/settings/test_privacy.py:

```diff
 @pytest.mark.django_db 
  def test_visible_follows_disabled(client, identity): 
      """ 
      Tests that disabling visible follows hides it from profile 
      """ 
      Config.set_identity(identity, "visible_follows", True) 
      response = client.get(identity.urls.view) 
-     assertContains(response, '<div class="view-options follows">', status_code=200) 
+     assertContains(response, 'follower', status_code=200)
      Config.set_identity(identity, "visible_follows", False) 
      response = client.get(identity.urls.view) 
-     assertNotContains(response, '<div class="view-options follows">', status_code=200) 
+     assertNotContains(response, 'follower', status_code=200)
```

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
Looks good now - you just need to rebase and fix the conflicts and we can land it!

**Comment by andrewgodwin** [comment]
Those test failures are from work I did on main that was bad - I'll merge in despite them, since I saw them pass before. Thanks!

**Pull request merged**
