### PR TITLE
Templatize robots.txt

### PR DESCRIPTION
**Pull request by tabletcorry**
The existing static robots.txt did not allow any method of adding additional disallowed agents.

Since a substantial majority of web traffic to my test instance is a few SEO crawlers, and this is likely to be true for others as well, add a method by which well-behaving robots can be blocked.

### CODE REVIEW

**Comment by tabletcorry** [comment]
I don't think the pre-commit error is due to my change 🤔

**Comment by shuuji3** [comment]
It looks like the pre-commit error is due to isort: https://github.com/PyCQA/isort/issues/2077

It was already fixed in v5.12.0, so I'll create a PR to upgrade the version.

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
I was thinking about doing this anyway, so thanks!

**Comment by tabletcorry** [comment]
The two that were annoying me the most for constant crawling are `TAKAHE_ROBOTS_TXT_DISALLOWED_USER_AGENTS='["AhrefsBot","SemrushBot"]'` in case anyone wants to copy a few easy ones.

**Pull request merged**
