### PR TITLE
Add pyupgrade with --py310-plus  in pre-commit

### PR DESCRIPTION
**Pull request by pauloxnet**
Since in the documentation for the contribution it is specified that Takahe requires Python 3.10 or higher I added pyupgrade with the relative Python version to pre-commit in order to automatically take advantage of the improvements to the new syntax, in particular for the typing. Tests seems barely faster with this PR.

### CODE REVIEW

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
Ah, nice, I sometimes forget that I can use the better typing syntax now.

If you could resolve the conflict here from all the other PRs today, I'll merge it in!

**Comment by pauloxnet** [comment]
> If you could resolve the conflict here from all the other PRs today, I'll merge it in!

I rebased the PR resolving conflicts and checked twice locally.
I think now the PR is ready again to be merged.

**Comment by andrewgodwin** [comment]
Amazing, thanks!

**Comment by pauloxnet** [comment]
Thanks to you 🙂

**Pull request merged**
