### PR TITLE
Fix header duplication during infinity scroll

### PR DESCRIPTION
**Pull request by humrochagf**
The infinity scroll at the Identity page was duplicating the header in each pagination event

### CODE REVIEW

**Comment by humrochagf** [comment]
Before:
Screenshot from 2023-01-29 18-55-44

After:
Screenshot from 2023-01-29 18-54-45

**Review by andrewgodwin — COMMENTED** [review]
You can use `request.htmx` rather than adding `headless`!

**Comment by humrochagf** [comment]
A nice feature from `django-htmx` I didn't know about it before :stuck_out_tongue_winking_eye:

**Review by andrewgodwin — APPROVED** [review]
Yeah, it's a really nice little package!

**Pull request merged**
