### PR TITLE
Fix inbox processing errors from pinned posts and non-Mastodon servers

### PR DESCRIPTION
**Pull request by osmaa**
If a post (interaction) comes in from AP inbox but no local author profile exists, fetch_actor will pull in both the identity AND its pinned posts, which the incoming post might have been. This would case a database integrity violation. We check for post existing again after syncing the actor.

Post processing also barfed on posts where content didn't follow Mastodon specs. For example, Kbin sets tag names in 'tag' attribute, instead of 'name' attribute.

### CODE REVIEW

**Comment by andrewgodwin** [comment]
This is presumably the fix for #592? Code looks good, you just need to run the pre-commit hooks locally in order to get the imports sorted correctly and a few other things (see https://docs.jointakahe.org/en/latest/contributing/#coding-guidelines)

**Comment by osmaa** [comment]
after being offline for a while, I figured out the pre-commit checks (thanks for the pointers!), should be good now.

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
Lovely, I appreciate it!

I've also added a new way of moving inbox messages to an `errored` state if you raise an `ActivityPubFormatError` - I'm not sure that anything here warrants it, but mentioning it in case you think something could benefit from that going in later.

**Comment by osmaa** [comment]
right, that change added a different way of dealing with attachments missing url. Removing mine in a separate PR.

**Pull request merged**
