### PR TITLE
Fix issues with hashtags being linkified when at the end of a URL (li…

### PR DESCRIPTION
**Pull request by TkTech**
…ke https://github.com/TkTech/notifico/blob/master/README.md?plain=1#L12) and other places they shouldn't be.

### CODE REVIEW

**Review by andrewgodwin — APPROVED** [review]

**Comment by TkTech** [comment]
This is not mergable as-is, because it cannot support hashtags split over multiple HTML tags which apparently Mastodon does.

**Comment by andrewgodwin** [comment]
OK, I will see if I can think of a different way later today.

**Comment by TkTech** [comment]
Mastodon appears to be using several different regexes in multiple stages, but I hesitate to look to closely as it's GPL.

**Comment by andrewgodwin** [comment]
I don't believe Mastodon supports preserving <a> hrefs directly, though, which helps a lot in this regard. I'm going to revert us to the same situation (only linkifying direct URLs, mentions, and hashtags) and we can figure out how to safely preserve actual links from other servers later on.

**Pull request closed without merging**
